version: '3'

services:
  db:
    container_name: portme-postgresql
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  server:
    container_name: portme-server
    image: node:latest
    ports:
      - "3333:3333"
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    command: sh -c "cd /server && yarn && yarn prisma db pull && yarn dev"
  web:
    container_name: portme-web
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    environment:
      - VITE_API_URL=http://localhost:3333
    command: sh -c "cd /web && yarn && yarn dev --host"
    depends_on:
      - server